// Auto-generated by translate-ilce-rehber.ts
// DO NOT EDIT MANUALLY - Run the script to regenerate

import { Locale } from "@/lib/i18n/config";

export interface IlceTranslation {
  metaDescription: string;
  kisaTanitim: string;
  seoBasliklar: string[];
  sss: { soru: string; cevap: string }[];
}

type TranslatedLocale = 'en' | 'ar' | 'de' | 'ru';

// Translations for all districts
export const ilceTranslations: Record<string, Record<TranslatedLocale, IlceTranslation>> = {
  "ortaca": {
    "en": {
      "metaDescription": "Ortaca district real estate, housing and land investment guide. Neighboring Dalyan, 20 minutes from the airport. Neighborhoods, prices and living guide.",
      "kisaTanitim": "Ortaca is a quiet and developing district located in the west of Muğla, only 20 minutes from Dalaman Airport. Ortaca, Dalyan's neighbor, attracts the attention of investors with both its natural beauties and affordable real estate prices.",
      "seoBasliklar": [
        "House and Land Prices for Sale in Ortaca 2026",
        "Ortaca Real Estate Market Evaluation",
        "Life Guide in Ortaca",
        "Investment Opportunities in Ortaca Neighborhoods",
        "Flats and Villas for Rent in Ortaca"
      ],
      "sss": [
        {
          "soru": "What are the housing prices in Ortaca?",
          "cevap": "As of 2026, flat prices in Ortaca vary between 18,000-35,000 TL per m²."
        },
        {
          "soru": "How far is Ortaca from the airport?",
          "cevap": "Dalaman Airport is only 20 km from Ortaca, approximately a 20-minute drive."
        },
        {
          "soru": "Which neighborhoods in Ortaca are suitable for investment?",
          "cevap": "Neighborhoods on Cumhuriyet, Karaburun and Dalyan roads stand out for investment."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل الاستثمار العقاري والإسكان والأراضي في منطقة أورتاكا. داليان المجاورة، على بعد 20 دقيقة من المطار. الأحياء والأسعار ودليل المعيشة.",
      "kisaTanitim": "أورتاكا هي منطقة هادئة ومتطورة تقع في غرب موغلا، على بعد 20 دقيقة فقط من مطار دالامان. تجذب أورتاكا، جارة داليان، انتباه المستثمرين بجمالها الطبيعي وأسعار العقارات المعقولة.",
      "seoBasliklar": [
        "أسعار المنازل والأراضي للبيع في أورتاكا 2026",
        "تقييم سوق العقارات في أورتاكا",
        "دليل الحياة في أورتاكا",
        "فرص الاستثمار في أحياء أورتاكا",
        "شقق وفلل للإيجار في أورتاكا"
      ],
      "sss": [
        {
          "soru": "ما هي أسعار المساكن في أورتاكا؟",
          "cevap": "اعتبارًا من عام 2026، تتراوح أسعار الشقق في أورتاكا بين 18.000-35.000 ليرة تركية للمتر المربع."
        },
        {
          "soru": "كم تبعد اورتاكا عن المطار؟",
          "cevap": "يقع مطار دالامان على بعد 20 كم فقط من أورتاكا، أي حوالي 20 دقيقة بالسيارة."
        },
        {
          "soru": "ما هي الأحياء في أورتاكا المناسبة للاستثمار؟",
          "cevap": "تتميز الأحياء الواقعة على طرق جمهوريت وكارابورون وداليان بالاستثمار."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilien-, Wohnungs- und Landinvestitionsführer für den Bezirk Ortaca. Benachbartes Dalyan, 20 Minuten vom Flughafen entfernt. Stadtviertel, Preise und Wohnführer.",
      "kisaTanitim": "Ortaca ist ein ruhiger und sich entwickelnder Bezirk im Westen von Muğla, nur 20 Minuten vom Flughafen Dalaman entfernt. Ortaca, Dalyans Nachbar, zieht sowohl mit seiner Naturschönheit als auch mit seinen erschwinglichen Immobilienpreisen die Aufmerksamkeit von Investoren auf sich.",
      "seoBasliklar": [
        "Haus- und Grundstückspreise zum Verkauf in Ortaca 2026",
        "Ortaca-Immobilienmarktbewertung",
        "Lebensführer in Ortaca",
        "Investitionsmöglichkeiten in Ortaca-Vierteln",
        "Wohnungen und Villen zur Miete in Ortaca"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Immobilienpreise in Ortaca?",
          "cevap": "Ab 2026 schwanken die Wohnungspreise in Ortaca zwischen 18.000 und 35.000 TL pro m²."
        },
        {
          "soru": "Wie weit ist Ortaca vom Flughafen entfernt?",
          "cevap": "Der Flughafen Dalaman liegt nur 20 km von Ortaca entfernt, etwa 20 Autominuten."
        },
        {
          "soru": "Welche Stadtteile in Ortaca eignen sich für Investitionen?",
          "cevap": "Stadtteile an den Straßen Cumhuriyet, Karaburun und Dalyan zeichnen sich durch Investitionen aus."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по инвестициям в недвижимость, жилье и землю в районе Ортача. Соседний Дальян, 20 минут от аэропорта. Районы, цены и путеводитель по жизни.",
      "kisaTanitim": "Ортача — тихий и развивающийся район, расположенный на западе Муглы, всего в 20 минутах от аэропорта Даламан. Ортаджа, сосед Дальяна, привлекает внимание инвесторов как своими природными красотами, так и доступными ценами на недвижимость.",
      "seoBasliklar": [
        "Цены на дом и землю на продажу в Ортаче в 2026 году",
        "Оценка рынка недвижимости Ортачи",
        "Путеводитель по жизни в Ортаке",
        "Инвестиционные возможности в окрестностях Ортачи",
        "Квартиры и виллы в аренду в Ортака"
      ],
      "sss": [
        {
          "soru": "Каковы цены на жилье в Ортача?",
          "cevap": "По состоянию на 2026 год цены на квартиры в Ортаке варьируются в пределах 18 000–35 000 TL за м²."
        },
        {
          "soru": "Как далеко Ортача от аэропорта?",
          "cevap": "Аэропорт Даламана находится всего в 20 км от Ортачи, примерно в 20 минутах езды."
        },
        {
          "soru": "Какие районы Ортачи подходят для инвестиций?",
          "cevap": "Районы на дорогах Джумхуриет, Карабурун и Дальян выделяются для инвестиций."
        }
      ]
    }
  },
  "dalyan": {
    "en": {
      "metaDescription": "Dalyan guide: Iztuzu Beach, Kaunos Ancient City, villa and real estate opportunities. Life and investment in Dalyan, the home of Caretta carettas.",
      "kisaTanitim": "Dalyan is a world-famous town with its UNESCO-protected Iztuzu Beach and caretta caretta sea turtles. The ancient city of Kaunos is an attractive destination for both tourism and real estate investment with its mud baths and unique nature.",
      "seoBasliklar": [
        "Villa and House Prices for Sale in Dalyan",
        "Dalyan Real Estate Investment Guide 2026",
        "Life in Dalyan: Advantages and Disadvantages",
        "Dalyan Tourism and Real Estate Potential",
        "Holiday Villa for Rent in Dalyan"
      ],
      "sss": [
        {
          "soru": "How much are villa prices in Dalyan?",
          "cevap": "Villa prices in Dalyan start from 4 million TL and can go up to 20 million TL, depending on the location."
        },
        {
          "soru": "Can foreigners buy property in Dalyan?",
          "cevap": "Yes, foreign nationals can buy property in Dalyan in accordance with legal procedures."
        },
        {
          "soru": "Which is the best neighborhood in Dalyan?",
          "cevap": "With its central location, Dalyan District and areas with canal views are ideal for nature lovers."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل داليان: شاطئ إزتوزو، مدينة كاونوس القديمة، الفلل والفرص العقارية. الحياة والاستثمار في داليان، موطن كاريتا كاريتاس.",
      "kisaTanitim": "داليان هي مدينة مشهورة عالميًا بشاطئ إيزتوزو المحمي من قبل اليونسكو وسلاحف كاريتا كاريتا البحرية. وتعتبر مدينة كاونوس القديمة وجهة جذابة للاستثمار السياحي والعقاري على حد سواء، حيث تتميز بحماماتها الطينية وطبيعتها الفريدة.",
      "seoBasliklar": [
        "أسعار الفلل والمنازل للبيع في داليان",
        "دليل داليان للاستثمار العقاري 2026",
        "الحياة في داليان: المزايا والعيوب",
        "داليان السياحة والعقارات المحتملة",
        "فيلا عطلة للإيجار في داليان"
      ],
      "sss": [
        {
          "soru": "ما هي أسعار الفيلات في داليان؟",
          "cevap": "تبدأ أسعار الفلل في داليان من 4 مليون ليرة تركية ويمكن أن تصل إلى 20 مليون ليرة تركية، حسب الموقع."
        },
        {
          "soru": "هل يمكن للأجانب شراء العقارات في داليان؟",
          "cevap": "نعم، يمكن للمواطنين الأجانب شراء العقارات في داليان وفقًا للإجراءات القانونية."
        },
        {
          "soru": "ما هو أفضل حي في داليان؟",
          "cevap": "بفضل موقعها المركزي، تعد منطقة داليان والمناطق المطلة على القناة مثالية لمحبي الطبيعة."
        }
      ]
    },
    "de": {
      "metaDescription": "Dalyan-Führer: Iztuzu-Strand, antike Stadt Kaunos, Villen- und Immobilienmöglichkeiten. Leben und Investitionen in Dalyan, der Heimat der Caretta Carettas.",
      "kisaTanitim": "Dalyan ist eine weltberühmte Stadt mit seinem UNESCO-geschützten Iztuzu-Strand und den Caretta-Caretta-Meeresschildkröten. Die antike Stadt Kaunos ist mit ihren Schlammbädern und ihrer einzigartigen Natur ein attraktives Reiseziel sowohl für den Tourismus als auch für Immobilieninvestitionen.",
      "seoBasliklar": [
        "Preise für Villen und Häuser zum Verkauf in Dalyan",
        "Dalyan Real Estate Investment Guide 2026",
        "Leben in Dalyan: Vor- und Nachteile",
        "Tourismus- und Immobilienpotenzial in Dalyan",
        "Ferienvilla zu vermieten in Dalyan"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Villenpreise in Dalyan?",
          "cevap": "Die Preise für Villen in Dalyan beginnen bei 4 Millionen TL und können je nach Standort bis zu 20 Millionen TL betragen."
        },
        {
          "soru": "Können Ausländer in Dalyan Immobilien kaufen?",
          "cevap": "Ja, Ausländer können in Dalyan im Einklang mit den gesetzlichen Bestimmungen Immobilien kaufen."
        },
        {
          "soru": "Welches ist das beste Viertel in Dalyan?",
          "cevap": "Aufgrund seiner zentralen Lage sind der Bezirk Dalyan und Gebiete mit Kanalblick ideal für Naturliebhaber."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по Дальяну: пляж Изтузу, древний город Каунос, виллы и возможности недвижимости. Жизнь и инвестиции в Дальяне, доме Каретта Кареттас.",
      "kisaTanitim": "Дальян — всемирно известный город с пляжем Изтузу, находящимся под охраной ЮНЕСКО, и морскими черепахами каретта-каретта. Древний город Каунос с его грязевыми ваннами и уникальной природой является привлекательным местом как для туризма, так и для инвестиций в недвижимость.",
      "seoBasliklar": [
        "Цены на виллы и дома на продажу в Дальяне",
        "Путеводитель по инвестициям в недвижимость Дальяна 2026",
        "Жизнь в Дальяне: преимущества и недостатки",
        "Дальян Туризм и потенциал недвижимости",
        "Вилла для отдыха в аренду в Дальяне"
      ],
      "sss": [
        {
          "soru": "Сколько стоят виллы в Дальяне?",
          "cevap": "Цены на виллы в Дальяне начинаются от 4 миллионов TL и могут доходить до 20 миллионов TL, в зависимости от местоположения."
        },
        {
          "soru": "Могут ли иностранцы купить недвижимость в Дальяне?",
          "cevap": "Да, иностранные граждане могут приобрести недвижимость в Дальяне в соответствии с юридическими процедурами."
        },
        {
          "soru": "Какой район в Дальяне лучший?",
          "cevap": "Благодаря центральному расположению район Дальян и районы с видом на канал идеально подходят для любителей природы."
        }
      ]
    }
  },
  "koycegiz": {
    "en": {
      "metaDescription": "Real estate opportunities with views of Köyceğiz Lake. Sultaniye Thermal Springs, natural life and affordable land prices. Köyceğiz investment guide.",
      "kisaTanitim": "Köyceğiz is a quiet district that hosts one of Türkiye's largest lagoon lakes and stands out with its thermal resources and untouched nature. Properties with Sultaniye Thermal Springs and lake views attract the attention of investors.",
      "seoBasliklar": [
        "Land and House for Sale in Köyceğiz",
        "Properties with Köyceğiz Lake View",
        "Köyceğiz Real Estate Market 2026",
        "Cost of Living in Köyceğiz",
        "Köyceğiz Investment Potential"
      ],
      "sss": [
        {
          "soru": "How much are land prices in Köyceğiz?",
          "cevap": "Zoned land prices in Köyceğiz vary between 2,000-6,000 TL per m²."
        },
        {
          "soru": "Is there a house with a lake view in Köyceğiz?",
          "cevap": "Yes, there are properties with lake views, especially in Ulucami and Köyceğiz District."
        },
        {
          "soru": "Where are Köyceğiz hot springs?",
          "cevap": "Sultaniye Thermal Springs is located on the shores of Köyceğiz Lake, accessible by boats."
        }
      ]
    },
    "ar": {
      "metaDescription": "فرص عقارية بإطلالات على بحيرة كويجيز. ينابيع السلطانية الحرارية والحياة الطبيعية وأسعار الأراضي المعقولة. دليل الاستثمار كويجيجيز.",
      "kisaTanitim": "Köyceğiz هي منطقة هادئة تضم واحدة من أكبر البحيرات الشاطئية في تركيا وتتميز بمواردها الحرارية وطبيعتها البكر. العقارات المطلة على ينابيع السلطان الحرارية والمطلة على البحيرة تجذب انتباه المستثمرين.",
      "seoBasliklar": [
        "أرض ومنزل للبيع في كويجيجيز",
        "عقارات مطلة على بحيرة كويجيز",
        "سوق كويجيجيز العقاري 2026",
        "تكلفة المعيشة في كويجيز",
        "إمكانات الاستثمار في Köyceğiz"
      ],
      "sss": [
        {
          "soru": "كم هي أسعار الأراضي في كويجيجيز؟",
          "cevap": "تتراوح أسعار الأراضي المخصصة في كويجيز بين 2000-6000 ليرة تركية لكل متر مربع."
        },
        {
          "soru": "هل يوجد منزل مطل على البحيرة في كويجيز؟",
          "cevap": "نعم، هناك عقارات مطلة على البحيرة، خاصة في منطقة أولوكامي وكويجيز."
        },
        {
          "soru": "أين تقع ينابيع كويجيجيز الساخنة؟",
          "cevap": "تقع ينابيع السلطان الحرارية على ضفاف بحيرة كويجيز، ويمكن الوصول إليها عن طريق القوارب."
        }
      ]
    },
    "ru": {
      "metaDescription": "Возможности недвижимости с видом на озеро Кейджегиз. Термальные источники Султание, естественная жизнь и доступные цены на землю. Инвестиционный путеводитель Кейджегиз.",
      "kisaTanitim": "Кёйджегиз — тихий район, в котором расположено одно из крупнейших лагунных озер Турции, и который выделяется своими термальными ресурсами и нетронутой природой. Недвижимость с термальными источниками Султание и видом на озеро привлекает внимание инвесторов.",
      "seoBasliklar": [
        "Земля и дом на продажу в Кёйджегиз",
        "Недвижимость с Видом на озеро Кёйджегиз",
        "Рынок недвижимости Кёйджегиз 2026",
        "Стоимость жизни в Кёйджегизе",
        "Инвестиционный потенциал Кёйджегиза"
      ],
      "sss": [
        {
          "soru": "Сколько стоят земли в Кёйджегизе?",
          "cevap": "Цены на зонированную землю в Кёйджегизе варьируются от 2 000 до 6 000 TL за м²."
        },
        {
          "soru": "Есть ли в Кёйджегизе дом с видом на озеро?",
          "cevap": "Да, есть недвижимость с видом на озеро, особенно в районах Улуками и Кёйджегиз."
        },
        {
          "soru": "Где находятся горячие источники Кейджегиз?",
          "cevap": "Термальные источники Султание расположены на берегу озера Кейджегиз, куда можно добраться на лодках."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilienmöglichkeiten mit Blick auf den Köyceğiz-See. Sultaniye-Thermalquellen, natürliches Leben und erschwingliche Grundstückspreise. Köyceğiz-Investitionsführer.",
      "kisaTanitim": "Köyceğiz ist ein ruhiger Bezirk, der einen der größten Lagunenseen Türkiyes beherbergt und sich durch seine Thermalquellen und unberührte Natur auszeichnet. Immobilien mit Sultaniye-Thermalquellen und Seeblick ziehen die Aufmerksamkeit von Investoren auf sich.",
      "seoBasliklar": [
        "Grundstück und Haus zum Verkauf in Köyceğiz",
        "Immobilien mit Blick auf den Köyceğiz-See",
        "Immobilienmarkt Köyceğiz 2026",
        "Lebenshaltungskosten in Köyceğiz",
        "Köyceğiz Investitionspotenzial"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Grundstückspreise in Köyceğiz?",
          "cevap": "Die Preise für Zonengrundstücke in Köyceğiz variieren zwischen 2.000 und 6.000 TL pro m²."
        },
        {
          "soru": "Gibt es ein Haus mit Seeblick in Köyceğiz?",
          "cevap": "Ja, es gibt Immobilien mit Seeblick, insbesondere in den Bezirken Ulucami und Köyceğiz."
        },
        {
          "soru": "Wo sind die heißen Quellen von Köyceğiz?",
          "cevap": "Die Sultaniye-Thermalquellen liegen am Ufer des Köyceğiz-Sees und sind mit Booten erreichbar."
        }
      ]
    }
  },
  "dalaman": {
    "en": {
      "metaDescription": "Dalaman Airport region real estate guide. Strategic location, agricultural lands and housing investment. Land and house prices in Dalaman.",
      "kisaTanitim": "Dalaman is the air transportation center of Muğla with its international airport. With its fertile agricultural lands, strategic location and developing infrastructure, it is an attractive district for both agriculture and real estate investments.",
      "seoBasliklar": [
        "Land Prices for Sale in Dalaman",
        "Real Estate Around Dalaman Airport",
        "Agricultural Land Investment in Dalaman",
        "Dalaman Housing Projects 2026",
        "Life and Transportation in Dalaman"
      ],
      "sss": [
        {
          "soru": "Does land investment in Dalaman make sense?",
          "cevap": "With its proximity to the airport and developing infrastructure, Dalaman has potential for land investment."
        },
        {
          "soru": "How much are house prices in Dalaman centre?",
          "cevap": "Flat prices in Dalaman center start from 1.5 million TL."
        },
        {
          "soru": "How far is Fethiye from Dalaman?",
          "cevap": "It is approximately 45 km, 40 minutes by road from Dalaman to Fethiye."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل العقارات في منطقة مطار دالامان. الموقع الاستراتيجي والأراضي الزراعية والإسكان الاستثماري. أسعار الأراضي والمنازل في دالامان.",
      "kisaTanitim": "دالامان هي مركز النقل الجوي لموغلا مع مطارها الدولي. وتتميز المنطقة بأراضيها الزراعية الخصبة وموقعها الاستراتيجي وبنيتها التحتية المتطورة، مما يجعلها منطقة جاذبة للاستثمارات الزراعية والعقارية.",
      "seoBasliklar": [
        "أسعار الأراضي للبيع في دالامان",
        "عقارات حول مطار دالامان",
        "استثمار الأراضي الزراعية في دالامان",
        "مشاريع الإسكان في دالامان 2026",
        "الحياة والنقل في دالامان"
      ],
      "sss": [
        {
          "soru": "هل الاستثمار في الأراضي في دالامان منطقي؟",
          "cevap": "بفضل قربها من المطار والبنية التحتية المتطورة، تتمتع دالامان بإمكانية الاستثمار في الأراضي."
        },
        {
          "soru": "كم هي أسعار المنازل في مركز دالامان؟",
          "cevap": "أسعار الشقق في مركز دالامان تبدأ من 1.5 مليون ليرة تركية."
        },
        {
          "soru": "كم تبعد فتحية عن دالامان؟",
          "cevap": "وتبعد حوالي 45 كم، 40 دقيقة برا من دالامان إلى فتحية."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilienführer für die Flughafenregion Dalaman. Strategische Lage, landwirtschaftliche Flächen und Wohnungsinvestitionen. Grundstücks- und Hauspreise in Dalaman.",
      "kisaTanitim": "Dalaman ist mit seinem internationalen Flughafen das Luftverkehrszentrum von Muğla. Mit seinen fruchtbaren landwirtschaftlichen Flächen, seiner strategischen Lage und der sich entwickelnden Infrastruktur ist es ein attraktiver Bezirk sowohl für die Landwirtschaft als auch für Immobilieninvestitionen.",
      "seoBasliklar": [
        "Grundstückspreise zum Verkauf in Dalaman",
        "Immobilien rund um den Flughafen Dalaman",
        "Investitionen in landwirtschaftliche Flächen in Dalaman",
        "Wohnprojekte in Dalaman 2026",
        "Leben und Transport in Dalaman"
      ],
      "sss": [
        {
          "soru": "Sind Landinvestitionen in Dalaman sinnvoll?",
          "cevap": "Aufgrund seiner Nähe zum Flughafen und der sich entwickelnden Infrastruktur verfügt Dalaman über Potenzial für Landinvestitionen."
        },
        {
          "soru": "Wie hoch sind die Immobilienpreise im Zentrum von Dalaman?",
          "cevap": "Die Pauschalpreise im Zentrum von Dalaman beginnen bei 1,5 Millionen TL."
        },
        {
          "soru": "Wie weit ist Fethiye von Dalaman entfernt?",
          "cevap": "Von Dalaman nach Fethiye sind es etwa 45 km, 40 Minuten auf der Straße."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости в регионе аэропорта Даламан. Стратегическое расположение, сельскохозяйственные угодья и инвестиции в жилье. Цены на землю и жилье в Даламане.",
      "kisaTanitim": "Даламан — авиатранспортный центр Муглы с международным аэропортом. Благодаря своим плодородным сельскохозяйственным землям, стратегическому расположению и развивающейся инфраструктуре, это привлекательный район как для сельского хозяйства, так и для инвестиций в недвижимость.",
      "seoBasliklar": [
        "Цены на землю для продажи в Даламане",
        "Недвижимость вокруг аэропорта Даламан",
        "Инвестиции в сельскохозяйственные земли в Даламане",
        "Жилищные проекты Даламана 2026",
        "Жизнь и транспорт в Даламане"
      ],
      "sss": [
        {
          "soru": "Имеет ли смысл инвестировать в землю в Даламане?",
          "cevap": "Благодаря близости к аэропорту и развивающейся инфраструктуре Даламан имеет потенциал для инвестиций в землю."
        },
        {
          "soru": "Сколько стоят дома в центре Даламана?",
          "cevap": "Цены на квартиры в центре Даламана начинаются от 1,5 млн TL."
        },
        {
          "soru": "На каком расстоянии Фетхие от Даламана?",
          "cevap": "Расстояние от Даламана до Фетхие составляет примерно 45 км и 40 минут по дороге."
        }
      ]
    }
  },
  "fethiye": {
    "en": {
      "metaDescription": "Fethiye real estate guide: Ölüdeniz, Göcek, Çalış locations. Villa, flat and land prices. Investment and life in Fethiye 2026.",
      "kisaTanitim": "Fethiye is one of the most popular tourism and life centers in Türkiye. It is a favorite of both local and foreign investors with the turquoise waters of Ölüdeniz, luxury marinas of Göcek and historical Kayaköy.",
      "seoBasliklar": [
        "Villa Prices for Sale in Fethiye 2026",
        "Ölüdeniz Real Estate Investment",
        "Fethiye Calis Region Housing",
        "Luxury Property Opportunities in Göcek",
        "House for Sale to Foreigners in Fethiye"
      ],
      "sss": [
        {
          "soru": "How much are villa prices in Fethiye?",
          "cevap": "Villa prices in Fethiye vary from 5 million TL to 50 million TL depending on location."
        },
        {
          "soru": "What is the most valuable area of ​​Fethiye?",
          "cevap": "Göcek, Ölüdeniz and Ovacık regions are the most valuable real estate areas of Fethiye."
        },
        {
          "soru": "Is it easy to buy foreign property in Fethiye?",
          "cevap": "Yes, Fethiye is one of the most active regions in Türkiye for foreign property purchases."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل العقارات في فتحية: مواقع أولودينيز، جوتشيك، كاليش. أسعار الفلل والشقق والأراضي. الاستثمار والحياة في فتحية 2026.",
      "kisaTanitim": "فتحية هي واحدة من مراكز السياحة والحياة الأكثر شعبية في تركيا. إنها وجهة مفضلة للمستثمرين المحليين والأجانب على حد سواء مع المياه الفيروزية في أولودينيز والمراسي الفاخرة في جوتشيك وكاياكوي التاريخية.",
      "seoBasliklar": [
        "أسعار الفلل للبيع في فتحية 2026",
        "أولودينيز للاستثمار العقاري",
        "إسكان منطقة فتحية كاليس",
        "فرص العقارات الفاخرة في جوتشيك",
        "منزل للبيع للأجانب في فتحية"
      ],
      "sss": [
        {
          "soru": "كم أسعار الفيلات في فتحية؟",
          "cevap": "تتراوح أسعار الفلل في فتحية من 5 مليون ليرة تركية إلى 50 مليون ليرة تركية حسب الموقع."
        },
        {
          "soru": "ما هي أغلى منطقة في فتحية؟",
          "cevap": "تعد مناطق جوتشيك وأولودينيز وأوفاجيك من أكثر المناطق العقارية قيمة في فتحية."
        },
        {
          "soru": "هل من السهل شراء العقارات الأجنبية في فتحية؟",
          "cevap": "نعم، فتحية هي واحدة من أكثر المناطق نشاطًا في تركيا لشراء العقارات الأجنبية."
        }
      ]
    },
    "de": {
      "metaDescription": "Fethiye-Immobilienführer: Standorte Ölüdeniz, Göcek, Çalış. Preise für Villen, Wohnungen und Grundstücke. Investition und Leben in Fethiye 2026.",
      "kisaTanitim": "Fethiye ist eines der beliebtesten Tourismus- und Lebenszentren in der Türkei. Mit dem türkisfarbenen Wasser von Ölüdeniz, den luxuriösen Yachthäfen von Göcek und dem historischen Kayaköy ist es bei einheimischen und ausländischen Investoren beliebt.",
      "seoBasliklar": [
        "Villa-Preise zum Verkauf in Fethiye 2026",
        "Immobilieninvestition in Ölüdeniz",
        "Wohnen in der Region Fethiye Calis",
        "Luxusimmobilienmöglichkeiten in Göcek",
        "Haus zum Verkauf an Ausländer in Fethiye"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Villenpreise in Fethiye?",
          "cevap": "Die Preise für Villen in Fethiye variieren je nach Standort zwischen 5 und 50 Millionen TL."
        },
        {
          "soru": "Was ist die wertvollste Gegend von Fethiye?",
          "cevap": "Die Regionen Göcek, Ölüdeniz und Ovacık sind die wertvollsten Immobiliengebiete von Fethiye."
        },
        {
          "soru": "Ist es einfach, ausländische Immobilien in Fethiye zu kaufen?",
          "cevap": "Ja, Fethiye ist eine der aktivsten Regionen in der Türkei für ausländische Immobilienkäufe."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости в Фетхие: Олюдениз, Гечек, Чалыш. Цены на виллу, квартиру и землю. Инвестиции и жизнь в Фетхие 2026.",
      "kisaTanitim": "Фетхие – один из самых популярных центров туризма и жизни в Турции. Это излюбленное место как местных, так и иностранных инвесторов благодаря бирюзовым водам Олюдениза, роскошным пристаням для яхт Гечека и историческому Каякёй.",
      "seoBasliklar": [
        "Цены на продажу вилл в Фетхие 2026",
        "Инвестиции в недвижимость Олюдениз",
        "Жилье в регионе Фетхие Чалыш",
        "Элитная недвижимость в Гечеке",
        "Дом для продажи иностранцам в Фетхие"
      ],
      "sss": [
        {
          "soru": "Сколько стоят виллы в Фетхие?",
          "cevap": "Цены на виллы в Фетхие варьируются от 5 до 50 миллионов TL в зависимости от местоположения."
        },
        {
          "soru": "Какой район Фетхие самый ценный?",
          "cevap": "Районы Гёчек, Олюдениз и Оваджик являются наиболее ценными районами недвижимости Фетхие."
        },
        {
          "soru": "Легко ли купить зарубежную недвижимость в Фетхие?",
          "cevap": "Да, Фетхие является одним из самых активных регионов Турции для покупки зарубежной недвижимости."
        }
      ]
    }
  },
  "marmaris": {
    "en": {
      "metaDescription": "Marmaris real estate market: İçmeler, Armutalan, Siteler regions. Sea view apartment and villa prices. Marmaris investment 2026.",
      "kisaTanitim": "Marmaris is known as the pearl of the Aegean with its magnificent bay and lively nightlife. It offers a strong market for real estate investment with yacht tourism, international visitors and developed infrastructure.",
      "seoBasliklar": [
        "Flat Prices for Sale in Marmaris",
        "Marmaris Sea View Residence",
        "Real Estate Investment in İçmeler",
        "Marmaris Marina District Properties",
        "Holiday House for Rent in Marmaris"
      ],
      "sss": [
        {
          "soru": "How much are apartment prices in Marmaris?",
          "cevap": "Sea view apartments in Marmaris start from 3 million TL."
        },
        {
          "soru": "Which is the best neighborhood in Marmaris?",
          "cevap": "Icmeler stands out with its quiet structure and Siteler stands out with its central location."
        },
        {
          "soru": "How is the rental income in Marmaris?",
          "cevap": "Since it is a touristic area, there is a high return potential in summer rentals."
        }
      ]
    },
    "ar": {
      "metaDescription": "سوق العقارات في مرمريس: مناطق إيسميلير، أرموتالان، سيتلر. أسعار الشقق والفلل المطلة على البحر. استثمار مرمريس 2026.",
      "kisaTanitim": "تُعرف مارماريس بأنها لؤلؤة بحر إيجة بخليجها الرائع وحياتها الليلية المفعمة بالحيوية. فهي توفر سوقًا قويًا للاستثمار العقاري مع سياحة اليخوت والزوار الدوليين والبنية التحتية المتطورة.",
      "seoBasliklar": [
        "أسعار الشقق للبيع في مارماريس",
        "مارماريس سي فيو ريزيدنس",
        "الاستثمار العقاري في ايسميلير",
        "عقارات منطقة مارينا مارماريس",
        "بيت عطلات للإيجار في مارماريس"
      ],
      "sss": [
        {
          "soru": "كم هي أسعار الشقق في مرمريس ؟",
          "cevap": "الشقق المطلة على البحر في مرمريس تبدأ أسعارها من 3 مليون ليرة تركية."
        },
        {
          "soru": "ما هو أفضل حي في مرمريس؟",
          "cevap": "تتميز إيسميلير ببنيتها الهادئة وتتميز سيتيلر بموقعها المركزي."
        },
        {
          "soru": "كيف هو دخل الإيجار في مارماريس؟",
          "cevap": "ونظرًا لأنها منطقة سياحية، فإن هناك عائدًا مرتفعًا على الإيجارات الصيفية."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilienmarkt Marmaris: Regionen İçmeler, Armutalan, Siteler. Preise für Apartments und Villen mit Meerblick. Marmaris-Investition 2026.",
      "kisaTanitim": "Marmaris ist mit seiner herrlichen Bucht und dem lebhaften Nachtleben als Perle der Ägäis bekannt. Es bietet einen starken Markt für Immobilieninvestitionen mit Yachttourismus, internationalen Besuchern und einer entwickelten Infrastruktur.",
      "seoBasliklar": [
        "Pauschalpreise zum Verkauf in Marmaris",
        "Residenz mit Meerblick in Marmaris",
        "Immobilieninvestition in İcmeler",
        "Immobilien im Marmaris Marina District",
        "Ferienhaus zu vermieten in Marmaris"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Wohnungspreise in Marmaris?",
          "cevap": "Apartments mit Meerblick in Marmaris gibt es ab 3 Millionen TL."
        },
        {
          "soru": "Welches ist das beste Viertel in Marmaris?",
          "cevap": "Icmeler zeichnet sich durch seine ruhige Struktur und Siteler durch seine zentrale Lage aus."
        },
        {
          "soru": "Wie sind die Mieteinnahmen in Marmaris?",
          "cevap": "Da es sich um ein touristisches Gebiet handelt, besteht bei der Sommervermietung ein hohes Renditepotenzial."
        }
      ]
    },
    "ru": {
      "metaDescription": "Рынок недвижимости Мармариса: регионы Ичмелер, Армуталан, Сителер. Цены на апартаменты и виллы с видом на море. Инвестиции в Мармарис 2026.",
      "kisaTanitim": "Мармарис известен как жемчужина Эгейского моря с его великолепной бухтой и оживленной ночной жизнью. Он предлагает сильный рынок для инвестиций в недвижимость с яхтенным туризмом, международными посетителями и развитой инфраструктурой.",
      "seoBasliklar": [
        "Цены на продажу квартир в Мармарисе",
        "Резиденция с видом на море в Мармарисе",
        "Инвестиции в недвижимость в Ичмелере",
        "Недвижимость в районе Марина Мармарис",
        "Дом для отдыха в аренду в Мармарисе"
      ],
      "sss": [
        {
          "soru": "Сколько стоят квартиры в Мармарисе?",
          "cevap": "Квартиры с видом на море в Мармарисе начинаются от 3 миллионов TL."
        },
        {
          "soru": "Какой район в Мармарисе лучший?",
          "cevap": "Ичмелер выделяется своей тихой структурой, а Сителер – центральным расположением."
        },
        {
          "soru": "Каков доход от аренды в Мармарисе?",
          "cevap": "Поскольку это туристический район, летняя аренда имеет высокий потенциал доходности."
        }
      ]
    }
  },
  "bodrum": {
    "en": {
      "metaDescription": "Bodrum luxury real estate market: Yalıkavak, Türkbükü, Gümüşlük. Villas, residences and marina properties. Bodrum investment guide 2026.",
      "kisaTanitim": "Bodrum is Türkiye's most prestigious and luxurious real estate market. With its whitewashed houses, world-famous nightlife and marinas, it is a favorite of both the local and international jet-set.",
      "seoBasliklar": [
        "Luxury Villa for Sale in Bodrum",
        "Yalıkavak Marina Real Estate Prices",
        "Bodrum Türkbükü Housing Investment",
        "Beachfront Property in Bodrum",
        "Bodrum Real Estate Trends 2026"
      ],
      "sss": [
        {
          "soru": "How much are villa prices in Bodrum?",
          "cevap": "Villa prices in Bodrum start from 10 million TL and can exceed 200 million TL."
        },
        {
          "soru": "What is the most expensive area in Bodrum?",
          "cevap": "Yalıkavak, Türkbükü and Gündoğan are the most valuable regions of Bodrum."
        },
        {
          "soru": "Is it possible to invest in Bodrum?",
          "cevap": "Bodrum is one of the real estate markets with the highest value increase in Türkiye."
        }
      ]
    },
    "ar": {
      "metaDescription": "سوق العقارات الفاخرة في بودروم: ياليكافاك، توركبوكو، غوموشلوك. فلل ومساكن وعقارات المارينا. دليل الاستثمار في بودروم 2026.",
      "kisaTanitim": "بودروم هي سوق العقارات الأكثر شهرة وفخامة في تركيا. بفضل منازلها المطلية باللون الأبيض والحياة الليلية والمراسي المشهورة عالميًا، فهي وجهة مفضلة لكل من الطائرات النفاثة المحلية والعالمية.",
      "seoBasliklar": [
        "فيلا فاخرة للبيع في بودروم",
        "أسعار عقارات ياليكافاك مارينا",
        "الاستثمار السكني في بودروم توركبوكو",
        "عقارات على شاطئ البحر في بودروم",
        "بودروم اتجاهات العقارات 2026"
      ],
      "sss": [
        {
          "soru": "ما هي أسعار الفلل في بودروم؟",
          "cevap": "تبدأ أسعار الفلل في بودروم من 10 مليون ليرة تركية ويمكن أن تتجاوز 200 مليون ليرة تركية."
        },
        {
          "soru": "ما هي أغلى منطقة في بودروم؟",
          "cevap": "تعتبر ياليكافاك وتوركبوكو وغوندوغان من أكثر المناطق قيمة في بودروم."
        },
        {
          "soru": "هل من الممكن الاستثمار في بودروم؟",
          "cevap": "بودروم هي واحدة من أسواق العقارات ذات أعلى زيادة في القيمة في تركيا."
        }
      ]
    },
    "de": {
      "metaDescription": "Luxusimmobilienmarkt in Bodrum: Yalıkavak, Türkbükü, Gümüşlük. Villen, Residenzen und Yachthafenimmobilien. Bodrum-Investitionsführer 2026.",
      "kisaTanitim": "Bodrum ist Türkiyes prestigeträchtigster und luxuriösester Immobilienmarkt. Mit seinen weiß getünchten Häusern, dem weltberühmten Nachtleben und den Jachthäfen ist es ein Favorit sowohl des lokalen als auch des internationalen Jetsets.",
      "seoBasliklar": [
        "Luxusvilla zum Verkauf in Bodrum",
        "Yalıkavak Marina Immobilienpreise",
        "Immobilieninvestition in Bodrum Türkbükü",
        "Strandgrundstück in Bodrum",
        "Immobilientrends in Bodrum 2026"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Villenpreise in Bodrum?",
          "cevap": "Die Preise für Villen in Bodrum beginnen bei 10 Millionen TL und können 200 Millionen TL überschreiten."
        },
        {
          "soru": "Was ist die teuerste Gegend in Bodrum?",
          "cevap": "Yalıkavak, Türkbükü und Gündoğan sind die wertvollsten Regionen Bodrums."
        },
        {
          "soru": "Ist es möglich, in Bodrum zu investieren?",
          "cevap": "Bodrum ist einer der Immobilienmärkte mit der höchsten Wertsteigerung in der Türkei."
        }
      ]
    },
    "ru": {
      "metaDescription": "Рынок элитной недвижимости Бодрума: Ялыкавак, Тюркбюкю, Гюмюшлюк. Виллы, резиденции и недвижимость на пристани. Инвестиционный путеводитель по Бодруму 2026.",
      "kisaTanitim": "Бодрум – самый престижный и роскошный рынок недвижимости Турции. С его побеленными домами, всемирно известной ночной жизнью и пристанями для яхт, он является излюбленным местом как местной, так и международной элиты.",
      "seoBasliklar": [
        "Роскошная вилла на продажу в Бодруме",
        "Цены на недвижимость в марине Ялыкавак",
        "Инвестиции в жилье в Бодруме, Тюркбюкю",
        "Недвижимость на берегу моря в Бодруме",
        "Тенденции недвижимости в Бодруме 2026"
      ],
      "sss": [
        {
          "soru": "Сколько стоят виллы в Бодруме?",
          "cevap": "Цены на виллы в Бодруме начинаются от 10 миллионов TL и могут превышать 200 миллионов TL."
        },
        {
          "soru": "Какой район в Бодруме самый дорогой?",
          "cevap": "Ялыкавак, Тюркбюкю и Гюндоган — самые ценные регионы Бодрума."
        },
        {
          "soru": "Можно ли инвестировать в Бодрум?",
          "cevap": "Бодрум является одним из рынков недвижимости с самым высоким ростом стоимости в Турции."
        }
      ]
    }
  },
  "milas": {
    "en": {
      "metaDescription": "Milas real estate guide: Airport area, Güllük coast, historical center. Affordable land and housing investment. Milas prices 2026.",
      "kisaTanitim": "Milas is a district that hosts Bodrum-Milas Airport and stands out with its historical texture and affordable prices. Güllük offers various opportunities to investors with its coastal region and productive olive groves.",
      "seoBasliklar": [
        "Land Prices for Sale in Milas",
        "Güllük Sahil Real Estate Investment",
        "Milas Center Housing Prices",
        "Agricultural Land in Milas",
        "Properties around Milas Bafa Lake"
      ],
      "sss": [
        {
          "soru": "Are land prices affordable in Milas?",
          "cevap": "Yes, Milas offers land investment opportunities at much more affordable prices than Bodrum."
        },
        {
          "soru": "How much are house prices in Güllük?",
          "cevap": "Flats near the sea in Güllük start from 2 million TL."
        },
        {
          "soru": "Is it close to Milas airport?",
          "cevap": "Yes, Milas-Bodrum Airport is only 15 km away from the center of Milas."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل ميلاس العقاري: منطقة المطار، ساحل غولوك، المركز التاريخي. الاستثمار في الأراضي والمساكن بأسعار معقولة. أسعار ميلاس 2026.",
      "kisaTanitim": "ميلاس هي المنطقة التي تستضيف مطار بودروم ميلاس وتتميز بنسيجها التاريخي وأسعارها المعقولة. تقدم جولوك فرصًا متنوعة للمستثمرين من خلال منطقتها الساحلية وبساتين الزيتون المنتجة.",
      "seoBasliklar": [
        "أسعار الأراضي للبيع في ميلاس",
        "جولوك ساهيل للاستثمار العقاري",
        "أسعار المساكن في مركز ميلاس",
        "أرض زراعية بميلاس",
        "عقارات حول بحيرة ميلاس بافا"
      ],
      "sss": [
        {
          "soru": "هل أسعار الأراضي معقولة في ميلاس؟",
          "cevap": "نعم، ميلاس توفر فرص استثمار الأراضي بأسعار معقولة أكثر بكثير من بودروم."
        },
        {
          "soru": "كم هي أسعار المنازل في غولوك ؟",
          "cevap": "الشقق القريبة من البحر في غولوك تبدأ من 2 مليون ليرة تركية."
        },
        {
          "soru": "هل هو قريب من مطار ميلاس؟",
          "cevap": "نعم، يقع مطار ميلاس بودروم على بعد 15 كم فقط من وسط ميلاس."
        }
      ]
    },
    "de": {
      "metaDescription": "Milas Immobilienführer: Flughafengebiet, Güllük-Küste, historisches Zentrum. Erschwingliche Grundstücks- und Wohninvestitionen. Milas-Preise 2026.",
      "kisaTanitim": "Milas ist ein Bezirk, der den Flughafen Bodrum-Milas beherbergt und sich durch seine historische Struktur und erschwinglichen Preise auszeichnet. Güllük bietet Investoren mit seiner Küstenregion und den produktiven Olivenhainen vielfältige Möglichkeiten.",
      "seoBasliklar": [
        "Grundstückspreise zum Verkauf in Milas",
        "Güllük Sahil Immobilieninvestition",
        "Immobilienpreise im Milas Center",
        "Landwirtschaftliches Land in Milas",
        "Immobilien rund um den Milas-Bafa-See"
      ],
      "sss": [
        {
          "soru": "Sind die Grundstückspreise in Milas erschwinglich?",
          "cevap": "Ja, Milas bietet Landinvestitionsmöglichkeiten zu viel günstigeren Preisen als Bodrum."
        },
        {
          "soru": "Wie hoch sind die Immobilienpreise in Güllük?",
          "cevap": "Wohnungen in Meeresnähe in Güllük gibt es ab 2 Millionen TL."
        },
        {
          "soru": "Liegt es in der Nähe des Flughafens Milas?",
          "cevap": "Ja, der Flughafen Milas-Bodrum ist nur 15 km vom Zentrum von Milas entfernt."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости Миласа: район аэропорта, побережье Гюллюк, исторический центр. Доступные инвестиции в землю и жилье. Цены на Милас 2026.",
      "kisaTanitim": "Милас – это район, в котором находится аэропорт Бодрум-Милас, он выделяется своей исторической структурой и доступными ценами. Гюллюк предлагает инвесторам различные возможности благодаря своему прибрежному региону и продуктивным оливковым рощам.",
      "seoBasliklar": [
        "Цены на землю для продажи в Миласе",
        "Инвестиции в недвижимость Гюллюк Сахиль",
        "Цены на жилье в Центре Милас",
        "Сельскохозяйственная земля в Миласе",
        "Недвижимость вокруг озера Милас Бафа"
      ],
      "sss": [
        {
          "soru": "Доступны ли цены на землю в Миласе?",
          "cevap": "Да, Милас предлагает возможности для инвестиций в землю по гораздо более доступным ценам, чем Бодрум."
        },
        {
          "soru": "Сколько стоят дома в Гюллюке?",
          "cevap": "Квартиры у моря в Гюллюке начинаются от 2 миллионов TL."
        },
        {
          "soru": "Это недалеко от аэропорта Милас?",
          "cevap": "Да, аэропорт Милас-Бодрум находится всего в 15 км от центра Миласа."
        }
      ]
    }
  },
  "mentese": {
    "en": {
      "metaDescription": "Menteşe (Muğla Center) real estate guide: Housing and land prices around the university, city center. Life in Menteşe 2026.",
      "kisaTanitim": "Menteşe is the central district and administrative heart of Muğla. Hosting Muğla Sıtkı Koçman University, it brings a stable housing demand and investment potential to the city center.",
      "seoBasliklar": [
        "Flat Prices for Sale in Menteşe",
        "Muğla Center Housing Investment",
        "Menteşe University Surroundings Real Estate",
        "House for Rent in Menteşe",
        "Muğla City Center Land"
      ],
      "sss": [
        {
          "soru": "How much are apartment prices in Menteşe?",
          "cevap": "Flat prices in Menteşe start from 1.5 million TL."
        },
        {
          "soru": "How much is student rent in Menteşe?",
          "cevap": "In areas close to the university, 1+1 flat rents are between 8,000-15,000 TL."
        },
        {
          "soru": "Is Menteşe suitable for investment?",
          "cevap": "Menteşe is a stable investment region as the university presence provides rental guarantee."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل العقارات في منتشه (مركز موغلا): أسعار المساكن والأراضي حول الجامعة ومركز المدينة. الحياة في منتيش 2026.",
      "kisaTanitim": "Menteşe هي المنطقة المركزية والقلب الإداري لمدينة موغلا. باستضافة جامعة موغلا سيتكي كوتشمان، فإنها توفر طلبًا مستقرًا على الإسكان وإمكانات الاستثمار في وسط المدينة.",
      "seoBasliklar": [
        "أسعار الشقق للبيع في Menteşe",
        "مركز موغلا للإسكان والاستثمار",
        "جامعة Menteşe المحيطة بالعقارات",
        "منزل للإيجار في Menteşe",
        "أرض وسط مدينة موغلا"
      ],
      "sss": [
        {
          "soru": "كم أسعار الشقق في منتيش ؟",
          "cevap": "أسعار الشقق في منتيش تبدأ من 1.5 مليون ليرة تركية."
        },
        {
          "soru": "كم هو إيجار الطالب في Menteşe؟",
          "cevap": "في المناطق القريبة من الجامعة، تتراوح أسعار إيجارات الشقق 1+1 بين 8,000-15,000 ليرة تركية."
        },
        {
          "soru": "هل Menteşe مناسب للاستثمار؟",
          "cevap": "مينتيش هي منطقة استثمارية مستقرة حيث أن وجود الجامعة يوفر ضمان الإيجار."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости Ментеше (центр Муглы): цены на жилье и землю вокруг университета, в центре города. Жизнь в Ментеше 2026.",
      "kisaTanitim": "Ментеше — центральный район и административный центр Муглы. Здесь находится Университет Мугла Ситки Кочмана, который обеспечивает стабильный спрос на жилье и инвестиционный потенциал в центре города.",
      "seoBasliklar": [
        "Цены на продажу квартир в Ментеше",
        "Инвестиции в жилищное строительство Центра Мугла",
        "Недвижимость в окрестностях Университета Ментеше",
        "Дом в аренду в Ментеше",
        "Земля в центре Муглы"
      ],
      "sss": [
        {
          "soru": "Сколько стоят квартиры в Ментеше?",
          "cevap": "Цены на квартиры в Ментеше начинаются от 1,5 млн TL."
        },
        {
          "soru": "Сколько стоит студенческая аренда в Ментеше?",
          "cevap": "В районах, близких к университету, арендная плата за квартиру 1+1 составляет от 8 000 до 15 000 TL."
        },
        {
          "soru": "Подходит ли Ментеше для инвестиций?",
          "cevap": "Ментеше является стабильным инвестиционным регионом, поскольку наличие университета обеспечивает гарантию аренды."
        }
      ]
    },
    "de": {
      "metaDescription": "Menteşe (Muğla Center) Immobilienführer: Immobilien- und Grundstückspreise rund um die Universität, Stadtzentrum. Leben in Menteşe 2026.",
      "kisaTanitim": "Menteşe ist der zentrale Bezirk und das Verwaltungszentrum von Muğla. Als Sitz der Universität Muğla Sıtkı Koçman bringt sie eine stabile Nachfrage nach Wohnraum und Investitionspotenzial in die Innenstadt.",
      "seoBasliklar": [
        "Wohnungspreise zum Verkauf in Menteşe",
        "Wohnungsinvestitionen im Muğla-Zentrum",
        "Immobilien in der Umgebung der Universität Menteşe",
        "Haus zu vermieten in Menteşe",
        "Land im Stadtzentrum von Muğla"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Wohnungspreise in Menteşe?",
          "cevap": "Die Pauschalpreise in Menteşe beginnen bei 1,5 Millionen TL."
        },
        {
          "soru": "Wie hoch ist die Studentenmiete in Menteşe?",
          "cevap": "In universitätsnahen Gebieten liegen die Mieten für 1+1-Wohnungen zwischen 8.000 und 15.000 TL."
        },
        {
          "soru": "Ist Menteşe für Investitionen geeignet?",
          "cevap": "Menteşe ist eine stabile Investitionsregion, da die Universitätspräsenz eine Mietgarantie bietet."
        }
      ]
    }
  },
  "datca": {
    "en": {
      "metaDescription": "Datça peninsula real estate guide: Palamutbükü, Knidos, almond gardens. Villa and land opportunities for those looking for a quiet life in 2026.",
      "kisaTanitim": "Datça is known as the paradise of those looking for a quiet life on the unique peninsula where the Aegean and the Mediterranean meet. It is a district focused on boutique tourism and natural life with its ancient Knidos ruins, almond flowers and untouched bays.",
      "seoBasliklar": [
        "Stone House for Sale in Datça",
        "Datça Peninsula Land Investment",
        "Natural Life in Datça",
        "Datça Real Estate Prices 2026",
        "Holiday House Investment in Datça"
      ],
      "sss": [
        {
          "soru": "What are the prices of stone houses in Datça?",
          "cevap": "Restored stone houses in Datça range between 3-10 million TL."
        },
        {
          "soru": "How to get to Datça?",
          "cevap": "It can be reached from Marmaris by ferry or road, and from Dalaman it takes 2.5 hours by car."
        },
        {
          "soru": "Is there winter in Datça?",
          "cevap": "Datça is a livable settlement all year round, thanks to its mild climate."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل العقارات في شبه جزيرة داتشا: Palamutbükü، Knidos، حدائق اللوز. فرص فلل وأراضي للباحثين عن حياة هادئة في 2026.",
      "kisaTanitim": "تُعرف داتشا بأنها جنة الباحثين عن حياة هادئة في شبه الجزيرة الفريدة حيث يلتقي بحر إيجه والبحر الأبيض المتوسط. إنها منطقة تركز على السياحة البوتيكية والحياة الطبيعية مع آثار كنيدوس القديمة وزهور اللوز والخلجان البكر.",
      "seoBasliklar": [
        "منزل حجري للبيع في داتشا",
        "استثمار أراضي شبه جزيرة داتشا",
        "الحياة الطبيعية في داتشا",
        "أسعار العقارات في داتشا 2026",
        "استثمار بيت العطلات في داتشا"
      ],
      "sss": [
        {
          "soru": "ما هي أسعار البيوت الحجرية في داتشا؟",
          "cevap": "تتراوح تكلفة المنازل الحجرية المرممة في داتشا بين 3-10 مليون ليرة تركية."
        },
        {
          "soru": "كيف تصل إلى داتشا؟",
          "cevap": "يمكن الوصول إليها من مرمريس بالعبارة أو البر، ومن دالامان تستغرق ساعتين ونصف بالسيارة."
        },
        {
          "soru": "هل هناك شتاء في داتشا ؟",
          "cevap": "تعتبر داتشا مستوطنة صالحة للعيش على مدار السنة، وذلك بفضل مناخها المعتدل."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilienführer auf der Halbinsel Datça: Palamutbükü, Knidos, Mandelgärten. Villen- und Grundstücksmöglichkeiten für diejenigen, die im Jahr 2026 ein ruhiges Leben suchen.",
      "kisaTanitim": "Datça ist als das Paradies für diejenigen bekannt, die ein ruhiges Leben auf der einzigartigen Halbinsel suchen, wo die Ägäis und das Mittelmeer zusammentreffen. Es ist ein Bezirk, der sich auf Boutique-Tourismus und Naturleben mit seinen antiken Knidos-Ruinen, Mandelblüten und unberührten Buchten konzentriert.",
      "seoBasliklar": [
        "Steinhaus zum Verkauf in Datça",
        "Landinvestition auf der Halbinsel Datça",
        "Natürliches Leben in Datça",
        "Datça-Immobilienpreise 2026",
        "Ferienhausinvestition in Datça"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Preise für Steinhäuser in Datça?",
          "cevap": "Restaurierte Steinhäuser in Datça kosten zwischen 3 und 10 Millionen TL."
        },
        {
          "soru": "Wie kommt man nach Datça?",
          "cevap": "Von Marmaris aus ist es mit der Fähre oder auf der Straße zu erreichen, von Dalaman aus dauert die Fahrt mit dem Auto 2,5 Stunden."
        },
        {
          "soru": "Gibt es Winter in Datça?",
          "cevap": "Datça ist dank seines milden Klimas das ganze Jahr über eine lebenswerte Siedlung."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости на полуострове Датча: Паламутбюкю, Книдос, миндальные сады. Возможности вилл и земельных участков для тех, кто ищет спокойную жизнь в 2026 году.",
      "kisaTanitim": "Датча известен как рай для тех, кто ищет спокойную жизнь на уникальном полуострове, где встречаются Эгейское и Средиземное моря. Это район, ориентированный на бутик-туризм и природную жизнь с древними руинами Книдоса, цветами миндаля и нетронутыми бухтами.",
      "seoBasliklar": [
        "Каменный дом на продажу в Датче",
        "Земельные инвестиции на полуострове Датча",
        "Природная жизнь в Датче",
        "Цены на недвижимость Датча 2026",
        "Инвестиции в дом для отдыха в Датче"
      ],
      "sss": [
        {
          "soru": "Каковы цены на каменные дома в Датча?",
          "cevap": "Отреставрированные каменные дома в Датче стоят от 3 до 10 миллионов турецких лир."
        },
        {
          "soru": "Как добраться до Датчи?",
          "cevap": "До него можно добраться из Мармариса на пароме или автомобилем, а из Даламана на машине потребуется 2,5 часа."
        },
        {
          "soru": "Есть ли в Датче зима?",
          "cevap": "Датча является поселением, пригодным для проживания круглый год, благодаря мягкому климату."
        }
      ]
    }
  },
  "ula": {
    "en": {
      "metaDescription": "Ula district real estate guide: Akyaka (Gökova), Gökova Bay view. Life in nature and affordable land prices 2026.",
      "kisaTanitim": "Ula is a green district with a magnificent view of Gökova Bay, home to the famous Akyaka town. Akyaka is the center of nature sports and ecotourism, with the title of Cittaslow (Calm City).",
      "seoBasliklar": [
        "House Prices for Sale in Akyaka",
        "Land with Ula Gökova View",
        "Akyaka Cittaslow Life",
        "Property in Nature in Ula",
        "Gökova Bay Real Estate Investment"
      ],
      "sss": [
        {
          "soru": "How much are house prices in Akyaka?",
          "cevap": "House prices in Akyaka start from 3 million TL and can reach 15 million TL."
        },
        {
          "soru": "Is it possible to build in Akyaka?",
          "cevap": "In Akyaka, traditional style construction is mandatory due to architectural protection rules."
        },
        {
          "soru": "How far is it from Ula to Muğla centre?",
          "cevap": "Ula is only 12 km from Muğla Menteşe."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل العقارات في منطقة أولا: أكياكا (جوكوفا)، إطلالة على خليج جوكوفا. الحياة في الطبيعة وأسعار الأراضي في متناول الجميع 2026.",
      "kisaTanitim": "أولا هي منطقة خضراء تتمتع بإطلالة رائعة على خليج جوكوفا، موطن مدينة أكياكا الشهيرة. أكياكا هي مركز الرياضات الطبيعية والسياحة البيئية، وتحمل لقب سيتاسلو (المدينة الهادئة).",
      "seoBasliklar": [
        "أسعار المنازل للبيع في اكياكا",
        "أرض مطلة على أولا جوكوفا",
        "حياة أكياكا سيتاسلو",
        "الملكية في الطبيعة في العلا",
        "خليج جوكوفا للاستثمار العقاري"
      ],
      "sss": [
        {
          "soru": "كم هي أسعار المنازل في أكياكا ؟",
          "cevap": "تبدأ أسعار المنازل في أكياكا من 3 ملايين ليرة تركية ويمكن أن تصل إلى 15 مليون ليرة تركية."
        },
        {
          "soru": "هل من الممكن البناء في اكياكا؟",
          "cevap": "في أكياكا، يعد البناء على الطراز التقليدي إلزاميًا بسبب قواعد الحماية المعمارية."
        },
        {
          "soru": "كم تبعد المسافة من أولا إلى مركز موغلا؟",
          "cevap": "تقع Ula على بعد 12 كم فقط من Muğla Menteşe."
        }
      ]
    },
    "de": {
      "metaDescription": "Immobilienführer für den Bezirk Ula: Akyaka (Gökova), Blick auf die Bucht von Gökova. Leben in der Natur und bezahlbare Grundstückspreise 2026.",
      "kisaTanitim": "Ula ist ein grüner Bezirk mit herrlichem Blick auf die Gökova-Bucht, die Heimat der berühmten Stadt Akyaka. Akyaka ist das Zentrum für Natursport und Ökotourismus und trägt den Titel Cittaslow (ruhige Stadt).",
      "seoBasliklar": [
        "Hauspreise zum Verkauf in Akyaka",
        "Grundstück mit Blick auf Ula Gökova",
        "Akyaka Cittaslow Leben",
        "Immobilien in der Natur in Ula",
        "Immobilieninvestition in der Bucht von Gökova"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Immobilienpreise in Akyaka?",
          "cevap": "Die Hauspreise in Akyaka beginnen bei 3 Millionen TL und können 15 Millionen TL erreichen."
        },
        {
          "soru": "Kann man in Akyaka bauen?",
          "cevap": "In Akyaka ist die Bauweise im traditionellen Stil aufgrund architektonischer Schutzvorschriften obligatorisch."
        },
        {
          "soru": "Wie weit ist es von Ula bis zum Zentrum von Muğla?",
          "cevap": "Ula ist nur 12 km von Muğla Menteşe entfernt."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости Ульского района: Акьяка (Гекова), вид на залив Гекова. Жизнь на природе и доступные цены на землю 2026.",
      "kisaTanitim": "Ула — зеленый район с великолепным видом на залив Гекова, где находится знаменитый город Акьяка. Акьяка - центр природных видов спорта и экотуризма, носящий название Читтаслоу (Спокойный город).",
      "seoBasliklar": [
        "Цены на жилье для продажи в Акьяке",
        "Земельный участок с видом на Улу Гёкова",
        "Акьяка Читтаслоу Жизнь",
        "Недвижимость на природе в Уле",
        "Инвестиции в недвижимость в заливе Гекова"
      ],
      "sss": [
        {
          "soru": "Сколько стоят дома в Акьяке?",
          "cevap": "Цены на жилье в Акьяке начинаются от 3 миллионов TL и могут достигать 15 миллионов TL."
        },
        {
          "soru": "Возможно ли строительство в Акьяке?",
          "cevap": "В Акьяке строительство в традиционном стиле является обязательным в соответствии с правилами охраны архитектуры."
        },
        {
          "soru": "Как далеко от Улы до центра Муглы?",
          "cevap": "Ула находится всего в 12 км от Муглы Ментеше."
        }
      ]
    }
  },
  "yatagan": {
    "en": {
      "metaDescription": "Yatağan real estate guide: Thermal power plant area, affordable land prices, Stratonikeia ancient city. Yatağan investment potential is 2026.",
      "kisaTanitim": "Yatağan is the industrial district of Muğla with its thermal power plants and mining sector. The district, which draws attention with its ancient Stratonikeia ruins and affordable real estate prices, offers housing opportunities for industrial workers.",
      "seoBasliklar": [
        "House and Land for Sale in Yatağan",
        "Yatağan Real Estate Prices 2026",
        "Affordable Housing in Yatağan",
        "Yatağan Industrial Zone Surroundings",
        "Stratonikeia Ancient City Surroundings Property"
      ],
      "sss": [
        {
          "soru": "Are housing prices affordable in Yatağan?",
          "cevap": "Yes, Yatağan has one of the most affordable housing markets in Muğla."
        },
        {
          "soru": "Are there job opportunities in Yatağan?",
          "cevap": "Thermal power plants and mining sectors are important sources of employment."
        },
        {
          "soru": "How long is it from Yatağan to Bodrum?",
          "cevap": "It is approximately 70 km, 1 hour by road from Yatağan to Bodrum."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل عقارات ياتاغان: منطقة محطة الطاقة الحرارية، أسعار الأراضي المعقولة، مدينة ستراتونيكيا القديمة. إمكانات الاستثمار في ياتاغان هي 2026.",
      "kisaTanitim": "ياتاغان هي المنطقة الصناعية في موغلا مع محطات الطاقة الحرارية وقطاع التعدين. توفر المنطقة، التي تلفت الانتباه بأطلال ستراتونيكيا القديمة وأسعار العقارات المعقولة، فرصًا للسكن لعمال الصناعة.",
      "seoBasliklar": [
        "منزل وأرض للبيع في ياتاغان",
        "أسعار عقارات ياتاغان 2026",
        "الإسكان بأسعار معقولة في ياتاغان",
        "محيط منطقة ياتاغان الصناعية",
        "ملكية محيطة مدينة ستراتونيكيا القديمة"
      ],
      "sss": [
        {
          "soru": "هل أسعار المساكن معقولة في ياتاغان؟",
          "cevap": "نعم، تمتلك ياتاغان واحدة من أكثر أسواق الإسكان بأسعار معقولة في موغلا."
        },
        {
          "soru": "هل توجد فرص عمل في ياتاغان؟",
          "cevap": "تعد محطات الطاقة الحرارية وقطاعات التعدين مصادر مهمة للعمالة."
        },
        {
          "soru": "كم المسافة من ياتاغان إلى بودروم؟",
          "cevap": "تبعد حوالي 70 كم، أي ساعة واحدة برا من ياتاغان إلى بودروم."
        }
      ]
    },
    "de": {
      "metaDescription": "Yatağan-Immobilienführer: Wärmekraftwerksgebiet, erschwingliche Grundstückspreise, antike Stadt Stratonikeia. Das Investitionspotenzial von Yatağan liegt im Jahr 2026.",
      "kisaTanitim": "Yatağan ist das Industriegebiet von Muğla mit seinen Wärmekraftwerken und dem Bergbausektor. Der Bezirk, der durch seine antiken Stratonikeia-Ruinen und erschwinglichen Immobilienpreise Aufmerksamkeit erregt, bietet Wohnmöglichkeiten für Industriearbeiter.",
      "seoBasliklar": [
        "Haus und Grundstück zum Verkauf in Yatağan",
        "Yatağan-Immobilienpreise 2026",
        "Bezahlbarer Wohnraum in Yatağan",
        "Umgebung des Industriegebiets Yatağan",
        "Anwesen in der Umgebung der antiken Stadt Stratonikeia"
      ],
      "sss": [
        {
          "soru": "Sind die Immobilienpreise in Yatağan erschwinglich?",
          "cevap": "Ja, Yatağan verfügt über einen der günstigsten Wohnungsmärkte in Muğla."
        },
        {
          "soru": "Gibt es Beschäftigungsmöglichkeiten in Yatağan?",
          "cevap": "Wärmekraftwerke und Bergbausektoren sind wichtige Beschäftigungsquellen."
        },
        {
          "soru": "Wie lange dauert es von Yatağan nach Bodrum?",
          "cevap": "Von Yatağan nach Bodrum sind es ungefähr 70 km und eine Stunde Autofahrt."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости Ятагана: район ТЭЦ, доступные цены на землю, древний город Стратоникея. Инвестиционный потенциал Ятагана – 2026 год.",
      "kisaTanitim": "Ятаган — промышленный район Муглы с тепловыми электростанциями и горнодобывающим сектором. Район, привлекающий внимание древними руинами Стратоникеи и доступными ценами на недвижимость, предлагает возможности для жилья для промышленных рабочих.",
      "seoBasliklar": [
        "Дом и земля на продажу в Ятагане",
        "Цены на недвижимость в Ятагане в 2026 году",
        "Доступное жилье в Ятагане",
        "Окрестности промышленной зоны Ятаган",
        "Недвижимость в окрестностях древнего города Стратоникея"
      ],
      "sss": [
        {
          "soru": "Доступны ли цены на жилье в Ятаган?",
          "cevap": "Да, в Ятагане один из самых доступных рынков жилья в Мугле."
        },
        {
          "soru": "Есть ли возможности трудоустройства в Ятагане?",
          "cevap": "Тепловые электростанции и горнодобывающая промышленность являются важными источниками занятости."
        },
        {
          "soru": "Сколько времени от Ятагана до Бодрума?",
          "cevap": "От Ятагана до Бодрума примерно 70 км, 1 час по дороге."
        }
      ]
    }
  },
  "kavaklidere": {
    "en": {
      "metaDescription": "Kavaklıdere district guide: Forest villages, natural life, affordable land prices. Kavaklıdere, the hidden paradise of Muğla, 2026.",
      "kisaTanitim": "Kavaklıdere is a quiet district in the north of Muğla, with natural beauties with its pine forests and plateaus. It offers economical land options for those looking for a rural life away from city noise.",
      "seoBasliklar": [
        "Land for Sale in Kavaklıdere",
        "Kavaklıdere Village House Prices",
        "Kavaklıdere Natural Life",
        "Kavaklıdere Forest Land",
        "Muğla Kavaklıdere Real Estate"
      ],
      "sss": [
        {
          "soru": "How much are land prices in Kavaklıdere?",
          "cevap": "Agricultural lands in Kavaklıdere are sold at very affordable prices."
        },
        {
          "soru": "How is life in Kavaklıdere?",
          "cevap": "Offering a rural and quiet life, Kavaklıdere is a district preferred by nature lovers."
        },
        {
          "soru": "How long is it from Kavaklıdere to Muğla?",
          "cevap": "Kavaklıdere is 45 km from Muğla Menteşe."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل منطقة كافاكليدير: قرى الغابات والحياة الطبيعية وأسعار الأراضي المعقولة. كافاكليدير، جنة موغلا المخفية، 2026.",
      "kisaTanitim": "كافاكليدير هي منطقة هادئة في شمال موغلا، تتميز بجمالها الطبيعي مع غابات الصنوبر والهضاب. يوفر خيارات أراضي اقتصادية لمن يبحثون عن حياة ريفية بعيدًا عن ضجيج المدينة.",
      "seoBasliklar": [
        "أرض للبيع في كافاكليدير",
        "أسعار منازل قرية كافاكليدير",
        "الحياة الطبيعية في كافاكليدير",
        "أرض غابات كافاكليدير",
        "موغلا كافاكليدير العقارية"
      ],
      "sss": [
        {
          "soru": "كم هي أسعار الأراضي في كافاكليدير؟",
          "cevap": "تباع الأراضي الزراعية في كافاكليدير بأسعار معقولة جدًا."
        },
        {
          "soru": "كيف هي الحياة في كافاكليدير؟",
          "cevap": "توفر منطقة كافاكليدير حياة ريفية وهادئة، وهي منطقة مفضلة لدى محبي الطبيعة."
        },
        {
          "soru": "كم المسافة من كافاكليدير إلى موغلا؟",
          "cevap": "تقع Kavaklıdere على بعد 45 كم من Muğla Menteşe."
        }
      ]
    },
    "de": {
      "metaDescription": "Bezirksführer Kavaklıdere: Walddörfer, natürliches Leben, erschwingliche Grundstückspreise. Kavaklıdere, das verborgene Paradies von Muğla, 2026.",
      "kisaTanitim": "Kavaklıdere ist ein ruhiger Bezirk im Norden von Muğla mit Naturschönheiten wie seinen Pinienwäldern und Hochebenen. Es bietet kostengünstige Landoptionen für diejenigen, die ein Leben auf dem Land abseits des Stadtlärms suchen.",
      "seoBasliklar": [
        "Grundstück zum Verkauf in Kavaklıdere",
        "Preise für Dorfhäuser in Kavaklıdere",
        "Kavaklıdere natürliches Leben",
        "Kavaklıdere-Waldland",
        "Muğla Kavaklıdere Immobilien"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Grundstückspreise in Kavaklıdere?",
          "cevap": "Landwirtschaftliche Flächen in Kavaklıdere werden zu sehr günstigen Preisen verkauft."
        },
        {
          "soru": "Wie ist das Leben in Kavaklıdere?",
          "cevap": "Kavaklıdere ist ein Bezirk, der von Naturliebhabern bevorzugt wird und ein ländliches und ruhiges Leben bietet."
        },
        {
          "soru": "Wie lange dauert es von Kavaklıdere nach Muğla?",
          "cevap": "Kavaklıdere liegt 45 km von Muğla Menteşe entfernt."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по району Каваклидере: Лесные деревни, природная жизнь, доступные цены на землю. Каваклидере, скрытый рай Муглы, 2026 год.",
      "kisaTanitim": "Каваклидере — тихий район на севере Муглы с природными красотами, сосновыми лесами и плато. Он предлагает экономичные варианты земли для тех, кто ищет сельскую жизнь вдали от городского шума.",
      "seoBasliklar": [
        "Земля на продажу в Каваклидере",
        "Цены на деревенские дома Каваклидере",
        "Каваклидере Природная жизнь",
        "Лесная земля Каваклидере",
        "Мугла Каваклидере Недвижимость"
      ],
      "sss": [
        {
          "soru": "Сколько стоят земли в Каваклидере?",
          "cevap": "Сельскохозяйственные земли в Каваклидере продаются по очень доступным ценам."
        },
        {
          "soru": "Как жизнь в Каваклидере?",
          "cevap": "Каваклидере — район, предпочитаемый любителями природы, где царит сельская и спокойная жизнь."
        },
        {
          "soru": "Сколько времени от Каваклидере до Муглы?",
          "cevap": "Каваклидере находится в 45 км от Мугла Ментеше."
        }
      ]
    }
  },
  "seydikemer": {
    "en": {
      "metaDescription": "Seydikemer real estate guide: Saklıkent Canyon, Eşen Plain agricultural lands. Affordable investment opportunities adjacent to Fethiye 2026.",
      "kisaTanitim": "Seydikemer is a district right next to Fethiye, hosting agricultural and nature tourism with Saklıkent Canyon and fertile Eşen Plain. It offers alternative affordable real estate options to Fethiye.",
      "seoBasliklar": [
        "Land for Sale in Seydikemer",
        "Seydikemer Agricultural Land Investment",
        "Real Estate Around Saklıkent",
        "Seydikemer Housing Prices 2026",
        "Fethiye Alternative Seydikemer"
      ],
      "sss": [
        {
          "soru": "How much are land prices in Seydikemer?",
          "cevap": "Zoned lands in Seydikemer are 40-50% more affordable than Fethiye."
        },
        {
          "soru": "How long is it from Seydikemer to Fethiye?",
          "cevap": "Seydikemer center is approximately 25 km from Fethiye."
        },
        {
          "soru": "Is there any property close to Saklıkent Canyon?",
          "cevap": "Yes, there are lands suitable for touristic investment around the canyon."
        }
      ]
    },
    "ar": {
      "metaDescription": "دليل عقارات سيديكيمير: وادي ساكليكنت، الأراضي الزراعية في سهل إيسن. فرص استثمارية ميسورة التكلفة بجوار فتحية 2026.",
      "kisaTanitim": "سيدي كيمر هي منطقة تقع بجوار فتحية مباشرةً، وتستضيف السياحة الزراعية والطبيعية مع وادي ساكليكنت وسهل إيسن الخصب. إنه يوفر خيارات عقارية بديلة بأسعار معقولة لفتحية.",
      "seoBasliklar": [
        "أرض للبيع في سيدي كيمير",
        "استثمار الأراضي الزراعية في سيديكمير",
        "عقارات حول ساكليكنت",
        "أسعار المساكن في سيديكيمير 2026",
        "فتحية البديل سيديكيمير"
      ],
      "sss": [
        {
          "soru": "كم أسعار الأراضي في سيدي كرم؟",
          "cevap": "الأراضي المخصصة في سيدي كيمير أقل تكلفة بنسبة 40-50٪ من فتحية."
        },
        {
          "soru": "كم المسافة من سيديكيمير إلى فتحية؟",
          "cevap": "يقع مركز سيديكيمير على بعد حوالي 25 كم من فتحية."
        },
        {
          "soru": "هل يوجد أي منشأة قريبة من Saklıkent Canyon؟",
          "cevap": "نعم يوجد أراضي مناسبة للاستثمار السياحي حول الوادي."
        }
      ]
    },
    "de": {
      "metaDescription": "Seydikemer-Immobilienführer: Saklıkent-Schlucht, landwirtschaftliche Flächen der Eşen-Ebene. Erschwingliche Investitionsmöglichkeiten neben Fethiye 2026.",
      "kisaTanitim": "Seydikemer ist ein Bezirk direkt neben Fethiye und beherbergt Landwirtschafts- und Naturtourismus mit der Saklıkent-Schlucht und der fruchtbaren Eşen-Ebene. Es bietet alternative erschwingliche Immobilienoptionen zu Fethiye.",
      "seoBasliklar": [
        "Grundstück zum Verkauf in Seydikemer",
        "Seydikemer-Investitionen in landwirtschaftliche Flächen",
        "Immobilien rund um Saklıkent",
        "Seydikemer-Wohnungspreise 2026",
        "Fethiye Alternative Seydikemer"
      ],
      "sss": [
        {
          "soru": "Wie hoch sind die Grundstückspreise in Seydikemer?",
          "cevap": "In Zonen aufgeteilte Grundstücke in Seydikemer sind 40-50 % günstiger als in Fethiye."
        },
        {
          "soru": "Wie lange dauert es von Seydikemer nach Fethiye?",
          "cevap": "Das Zentrum von Seydikemer liegt etwa 25 km von Fethiye entfernt."
        },
        {
          "soru": "Gibt es eine Unterkunft in der Nähe der Saklıkent-Schlucht?",
          "cevap": "Ja, rund um den Canyon gibt es Gebiete, die für touristische Investitionen geeignet sind."
        }
      ]
    },
    "ru": {
      "metaDescription": "Путеводитель по недвижимости в Сейдикемере: каньон Саклыкент, сельскохозяйственные угодья равнины Эшен. Доступные инвестиционные возможности рядом с Фетхие 2026.",
      "kisaTanitim": "Сейдикемер — это район рядом с Фетхие, где расположен сельскохозяйственный и природный туризм с каньоном Саклыкент и плодородной равниной Эшен. Он предлагает альтернативные доступные варианты недвижимости в Фетхие.",
      "seoBasliklar": [
        "Земля на продажу в Зейдикемере",
        "Инвестиции в сельскохозяйственные земли Сейдикемера",
        "Недвижимость вокруг Саклыкента",
        "Цены на жилье в Сейдикемере в 2026 году",
        "Альтернатива Фетхие Сейдикемер"
      ],
      "sss": [
        {
          "soru": "Сколько стоят земли в Зейдикемере?",
          "cevap": "Зонированные земли в Сейдикемере на 40-50% доступнее, чем в Фетхие."
        },
        {
          "soru": "Сколько времени от Сейдикемера до Фетхие?",
          "cevap": "Центр Сейдикемера находится примерно в 25 км от Фетхие."
        },
        {
          "soru": "Есть ли какая-либо недвижимость недалеко от отеля Каньон Саклыкент?",
          "cevap": "Да, вокруг каньона есть земли, подходящие для туристических инвестиций."
        }
      ]
    }
  }
};

// Helper function to get translated content
export function getIlceTranslation(slug: string, locale: Locale): IlceTranslation | null {
  if (locale === 'tr') return null; // Turkish is in the main data file

  const translations = ilceTranslations[slug];
  if (!translations) return null;

  return translations[locale as TranslatedLocale] || null;
}
