import { config } from 'dotenv';
config();

import fs from 'fs';
import path from 'path';
import translate from 'google-translate-api-x';
import { ilceRehberleri } from '../data/ilce-rehber';

// Districts that are missing German translations
const missingDeDistricts = ['koycegiz', 'mentese'];

async function translateText(text: string): Promise<string> {
  if (!text || text.trim() === '') return '';

  try {
    const result = await translate(text, {
      from: 'tr',
      to: 'de',
    });
    return result.text;
  } catch (error) {
    console.error(`Translation error:`, error);
    throw error;
  }
}

async function main() {
  console.log('='.repeat(70));
  console.log('EKSIK ALMANCA CEVIRILERI TAMAMLAMA');
  console.log('='.repeat(70));

  // Read current translations file
  const translationsPath = path.join(__dirname, '../data/ilce-rehber-i18n.ts');
  let fileContent = fs.readFileSync(translationsPath, 'utf-8');

  // Extract the JSON object from the file
  const jsonMatch = fileContent.match(/export const ilceTranslations[^=]*=\s*(\{[\s\S]*?\});/);
  if (!jsonMatch) {
    console.error('Could not extract translations from file');
    return;
  }

  const translations = JSON.parse(jsonMatch[1]);

  for (const slug of missingDeDistricts) {
    const ilce = ilceRehberleri.find(i => i.slug === slug);
    if (!ilce) {
      console.log(`[HATA] Ilce bulunamadi: ${slug}`);
      continue;
    }

    console.log(`\n[ILCE] ${ilce.ad} (${slug})`);
    console.log(`    → German cevriliyor...`);

    try {
      // Translate all texts with delays to avoid rate limiting
      const metaDescription = await translateText(ilce.metaDescription);
      await new Promise((r) => setTimeout(r, 1000));

      const kisaTanitim = await translateText(ilce.kisaTanitim);
      await new Promise((r) => setTimeout(r, 1000));

      // Translate SEO titles one by one
      const seoBasliklar: string[] = [];
      for (const baslik of ilce.seoBasliklar) {
        const translated = await translateText(baslik);
        seoBasliklar.push(translated);
        await new Promise((r) => setTimeout(r, 800));
      }

      // Translate FAQ one by one
      const sss: { soru: string; cevap: string }[] = [];
      for (const faq of ilce.sss) {
        const soru = await translateText(faq.soru);
        await new Promise((r) => setTimeout(r, 800));
        const cevap = await translateText(faq.cevap);
        await new Promise((r) => setTimeout(r, 800));
        sss.push({ soru, cevap });
      }

      // Add German translation to the district
      translations[slug].de = {
        metaDescription,
        kisaTanitim,
        seoBasliklar,
        sss,
      };

      console.log(`    ✓ German tamamlandi`);

      // Wait between districts
      await new Promise((r) => setTimeout(r, 2000));

    } catch (error) {
      console.error(`  [HATA] ${ilce.ad} - de:`, error);
    }
  }

  // Generate the updated file
  const updatedContent = `// Auto-generated by translate-ilce-rehber.ts
// DO NOT EDIT MANUALLY - Run the script to regenerate

import { Locale } from "@/lib/i18n/config";

export interface IlceTranslation {
  metaDescription: string;
  kisaTanitim: string;
  seoBasliklar: string[];
  sss: { soru: string; cevap: string }[];
}

type TranslatedLocale = 'en' | 'ar' | 'de' | 'ru';

// Translations for all districts
export const ilceTranslations: Record<string, Record<TranslatedLocale, IlceTranslation>> = ${JSON.stringify(translations, null, 2)};

// Helper function to get translated content
export function getIlceTranslation(slug: string, locale: Locale): IlceTranslation | null {
  if (locale === 'tr') return null; // Turkish is in the main data file

  const translations = ilceTranslations[slug];
  if (!translations) return null;

  return translations[locale as TranslatedLocale] || null;
}
`;

  fs.writeFileSync(translationsPath, updatedContent, 'utf-8');

  console.log('\n' + '='.repeat(70));
  console.log('EKSIK CEVIRILER TAMAMLANDI');
  console.log(`Dosya: ${translationsPath}`);
  console.log('='.repeat(70));
}

main().catch(console.error);
