import { config } from 'dotenv';
config();

import fs from 'fs';
import path from 'path';
import translate from 'google-translate-api-x';
import { ilceRehberleri, IlceRehber } from '../data/ilce-rehber';

const targetLocales = ['en', 'ar', 'de', 'ru'] as const;
type TargetLocale = (typeof targetLocales)[number];

const localeNames: Record<TargetLocale, string> = {
  en: 'English',
  ar: 'Arabic',
  de: 'German',
  ru: 'Russian',
};

interface IlceTranslation {
  metaDescription: string;
  kisaTanitim: string;
  seoBasliklar: string[];
  sss: { soru: string; cevap: string }[];
}

type IlceTranslations = Record<string, Record<TargetLocale, IlceTranslation>>;

async function translateText(text: string, targetLang: string): Promise<string> {
  if (!text || text.trim() === '') return '';

  try {
    const result = await translate(text, {
      from: 'tr',
      to: targetLang,
    });
    return result.text;
  } catch (error) {
    console.error(`Translation error for ${targetLang}:`, error);
    throw error;
  }
}

async function translateIlce(ilce: IlceRehber, locale: TargetLocale): Promise<IlceTranslation> {
  console.log(`    → ${localeNames[locale]} cevriliyor...`);

  // Translate all texts
  const [metaDescription, kisaTanitim] = await Promise.all([
    translateText(ilce.metaDescription, locale),
    translateText(ilce.kisaTanitim, locale),
  ]);

  // Small delay to avoid rate limiting
  await new Promise((r) => setTimeout(r, 300));

  // Translate SEO titles
  const seoBasliklar: string[] = [];
  for (const baslik of ilce.seoBasliklar) {
    const translated = await translateText(baslik, locale);
    seoBasliklar.push(translated);
    await new Promise((r) => setTimeout(r, 200));
  }

  // Translate FAQ
  const sss: { soru: string; cevap: string }[] = [];
  for (const faq of ilce.sss) {
    const [soru, cevap] = await Promise.all([
      translateText(faq.soru, locale),
      translateText(faq.cevap, locale),
    ]);
    sss.push({ soru, cevap });
    await new Promise((r) => setTimeout(r, 200));
  }

  console.log(`    ✓ ${localeNames[locale]} tamamlandi`);

  return {
    metaDescription,
    kisaTanitim,
    seoBasliklar,
    sss,
  };
}

async function main() {
  console.log('='.repeat(70));
  console.log('ILCE REHBER CEVIRISI BASLADI');
  console.log('='.repeat(70));
  console.log(`\nToplam ${ilceRehberleri.length} ilce, ${targetLocales.length} dil\n`);

  const translations: IlceTranslations = {};

  for (const ilce of ilceRehberleri) {
    console.log(`\n[ILCE] ${ilce.ad} (${ilce.slug})`);
    translations[ilce.slug] = {} as Record<TargetLocale, IlceTranslation>;

    for (const locale of targetLocales) {
      try {
        translations[ilce.slug][locale] = await translateIlce(ilce, locale);
      } catch (error) {
        console.error(`  [HATA] ${ilce.ad} - ${locale}:`, error);
      }

      // Delay between locales
      await new Promise((r) => setTimeout(r, 500));
    }
  }

  // Generate the i18n file
  const outputPath = path.join(__dirname, '../data/ilce-rehber-i18n.ts');

  const fileContent = `// Auto-generated by translate-ilce-rehber.ts
// DO NOT EDIT MANUALLY - Run the script to regenerate

import { Locale } from "@/lib/i18n/config";

export interface IlceTranslation {
  metaDescription: string;
  kisaTanitim: string;
  seoBasliklar: string[];
  sss: { soru: string; cevap: string }[];
}

type TranslatedLocale = 'en' | 'ar' | 'de' | 'ru';

// Translations for all districts
export const ilceTranslations: Record<string, Record<TranslatedLocale, IlceTranslation>> = ${JSON.stringify(translations, null, 2)};

// Helper function to get translated content
export function getIlceTranslation(slug: string, locale: Locale): IlceTranslation | null {
  if (locale === 'tr') return null; // Turkish is in the main data file

  const translations = ilceTranslations[slug];
  if (!translations) return null;

  return translations[locale as TranslatedLocale] || null;
}
`;

  fs.writeFileSync(outputPath, fileContent, 'utf-8');

  console.log('\n' + '='.repeat(70));
  console.log('CEVIRI TAMAMLANDI');
  console.log(`Dosya: ${outputPath}`);
  console.log('='.repeat(70));
}

main().catch(console.error);
